Thank you for using the KPF-CC Cadence Webform! This is big step towards codifying the use and best practices of the KPF-CC queue, which will become an official supported service by Keck Observatory. Here we describe the motivation for this tool. There are three primary reasons for the creation of this tool. 

First, we needed a robust, intuitive, and easy to use interface for PI's to submit targets to KPF-CC auto-scheduler algorithm in both a "language" and a format that the software understands. We must establish a shared language between the PI and the algorithm. Both must understand exactly what the other means for each of the parameters which together translate to a full observing strategy. Next, we needed a common format that all PI's use so that it is then easy to input all the information into the auto-scheduler. 

Second, in addition to producing a machine-readable file for the auto-scheduler, we wanted a way to produce a human-readable report that can be submitted to the TAC for their review and consideration. Starting with the Call for Proposals for the 2025A semester, PI's who wish to join the queue and submit a Keck proposal to any TAC will be required to submit targets to the queue and produce a report which will be included in their proposal. The Cadence Webform will become a natural part of the proposal writing and submission process. This webform forces the PI to consider their targets and observational strategy before proposing, thus producing better planned programs.
In the past, we have anecdotally seen observing requests that are not feasible to be completed and therefore leave a portion of their award unused. While the queue always finds something to observe so that the telescope is never idle, this is highly inefficient in terms of the use of the queue and the award from the TAC. Through the Cadence Webform and the report to be submitted with a proposal, the TAC will have additional information on the proposed program which they can consider in their review. Requests deemed Definitely Not Feasible will need to be justified as to why more time is asked for than can be used. Each TAC will have to decide for itself if and how to use this added information. 

Third, Keck Observatory allocates nights to awarded programs based on the requests from individual PI's. This works well for classically scheduled observations, but not for the queue. We wish to change the way the queue is allocated time: not on a program by program basis, but as if the queue itself is the program. Then we can ask, and try to answer, the question: what are the best nights for the general success of the queue as a whole? 
In order to do this, we have developed new software that we call "Optimal Allocation". This algorithm takes in the requests from all the PI's and determines what nights would be ideal to be allocated to the queue while trying to maximize the completion of as many requests as possible. We believe we can boost the completion rates of more requests this way than the current system where awarded nights don't always match the best nights for the queue. 
In order to run Optimal Allocation, we require all the requests for a given semester at the before the Keck Observatory schedule is built and the awards are announced. The easiest way to do this is to require all requests be submitted to the queue at the time of the proposal submission. And in order to require this, we needed an easy to use system to submit requests, hence the Cadence Webform. 
With all requests submitted at the time of the proposal deadline, we will cut the requests based on which programs are awarded time, then use those requests to determine the optimal allocation and simultaneously simulate the entire semester's observations. 

We thank you for your participation in the KPF-CC Cadence Webform! If you have any questions, please do not hesitate to reach out to the Project Scientist, Jack Lubin, at [jblubin@astro.ucla.edu](jblubin@astro.ucla.edu).